In [1]:
import torch

In [3]:
x = torch.arange(12) #0-12的张量数组
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
x.shape

torch.Size([2, 3, 4])

In [10]:
x.numel()#number of element

12

In [8]:
x =x.reshape(3,4)#改变形状
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
a = torch.zeros((2,3,4))
b = torch.ones((2,3,4))

In [16]:
#运算符按照对应元素运行 ** 求幂
torch.exp(x)

tensor([[[2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183]],

        [[2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183]]])

In [26]:
#dim 在size的对应dim上cat
torch.cat((a,b),dim=2)

tensor([[[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]]])

In [27]:
x.sum()

tensor(24.)

In [44]:
#广播机制
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [42]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
#索引&切片


In [49]:
#zeors_like()
#x+=y 原地操作，x=x+y 创建新变量
#大小为1的张量转换为标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [52]:
import os

os.makedirs(os.path.join('data'), exist_ok=True)
data_file = os.path.join( 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [55]:
import pandas as pd

data = pd.read_csv("/data/house_tiny.csv")
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [58]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]  #index location
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


C:\Users\yang\AppData\Local\Temp/ipykernel_5092/3818857219.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


对于inputs中的类别值或离散值，我们将“NaN”视为一个类别。 由于“巷子类型”（“Alley”）列只接受两种类型的类别值“Pave”和“NaN”， pandas可以自动将此列转换为两列“Alley_Pave”和“Alley_nan”。 巷子类型为“Pave”的行会将“Alley_Pave”的值设置为1，“Alley_nan”的值设置为0。 缺少巷子类型的行会将“Alley_Pave”和“Alley_nan”分别设置为0和1。

In [62]:
inputs = pd.get_dummies(inputs, dummy_na=True)# one-hot encoding
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [61]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [74]:
A = torch.arange(40, dtype=torch.float32).reshape(2, 5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.],
          [24., 26., 28., 30.],
          [32., 34., 36., 38.]],
 
         [[40., 42., 44., 46.],
          [48., 50., 52., 54.],
          [56., 58., 60., 62.],
          [64., 66., 68., 70.],
          [72., 74., 76., 78.]]]))

In [81]:
A.sum()

tensor(780.)

一个与求和相关的量是平均值（mean或average）。 我们通过将总和除以元素总数来计算平均值。 在代码中，我们可以调用函数来计算任意形状张量的平均值。

同样，计算平均值的函数也可以沿指定轴降低张量的维度。

In [82]:
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [83]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

但是，有时在调用函数来计算总和或均值时保持轴数不变会很有用。

In [87]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A.shape, sum_A,A.shape

(torch.Size([2, 1, 4]),
 tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 5, 4]))

In [93]:
A,A/sum_A,(A/sum_A).shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
          [0.1000, 0.1111, 0.1200, 0.1273],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.3000, 0.2889, 0.2800, 0.2727],
          [0.4000, 0.3778, 0.3600, 0.3455]],
 
         [[0.1429, 0.1448, 0.1467, 0.1484],
          [0.1714, 0.1724, 0.1733, 0.1742],
          [0.2000, 0.2000, 0.2000, 0.2000],
          [0.2286, 0.2276, 0.2267, 0.2258],
          [0.2571, 0.2552, 0.2533, 0.2516]]]),
 torch.Size([2, 5, 4]))

In [95]:
A,A.cumsum(axis=0)#dim =3 axis=0时0轴为“矩阵个数”

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]))

点积 torch.dot() or torch.sum(x * y)->对应元素相乘求和

在代码中使用张量表示矩阵-向量积，我们使用mv函数。 当我们为矩阵A和向量x调用torch.mv(A, x)时，会执行矩阵-向量积。 注意，A的列维数（沿轴1的长度）必须与x的维数（其长度）相同。

矩阵间乘法用 torch.mm(A, B)

In [96]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

自动求导

In [10]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [12]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
x.grad  # 默认值是None

In [14]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [15]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [107]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()#注释掉结果 tensor([ 1.,  5.,  9., 13.])
y = x.sum()
print(y)
y.backward()
x.grad

tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])

In [110]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [18]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [112]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [117]:
x.grad.zero_()
f = torch.exp(x)
f.sum().backward()
x.grad

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

In [123]:
con = torch.tensor(4,dtype=torch.float32,requires_grad=True)
y = torch.exp(con)
y.backward()
con.grad

tensor(54.5981)

In [124]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [128]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [131]:
a,d,d/a,a.grad

(tensor(0.9892, requires_grad=True),
 tensor(1012.9178, grad_fn=<MulBackward0>),
 tensor(1024., grad_fn=<DivBackward0>),
 tensor(1024.))

In [133]:
x = torch.tensor([2., 1.], requires_grad=True)
x.view(1,2).sum().backward()
x.grad

tensor([1., 1.])

In [2]:
from torch.distributions import multinomial

In [4]:
fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1, fair_probs)

Multinomial()

生成线性模型 $y = Xw+b+\epsilon$ 的 数据

In [4]:
def synthetic_data(w, b, num_examples):  #@save
    """生成y=Xw+b+噪声"""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)

**yield** 关键字的用法

In [22]:
def foo():
    print("starting...")
    while True:
        res = yield 4
        print("res:",res)
foo()
print('example')
next(foo())
#print(next(g))
#print("*"*20)
#print(next(g))
#ref:https://blog.csdn.net/mieleizhi0522/article/details/82142856

example
starting...


4

In [2]:
import random
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # 这些样本是随机读取的，没有特定的顺序
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [5]:
batch_size = 10

for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

tensor([[ 0.0167,  1.9948],
        [-1.5577, -2.0392],
        [ 1.6822,  0.2408],
        [-0.2817,  0.5112],
        [ 1.9325,  0.9046],
        [ 1.0369, -1.7116],
        [ 1.0387, -0.1342],
        [-0.1598, -0.3615],
        [ 0.8507,  0.9372],
        [ 0.5447,  0.8431]]) 
 tensor([[-2.5586],
        [ 8.0186],
        [ 6.7538],
        [ 1.9035],
        [ 4.9865],
        [12.1016],
        [ 6.7357],
        [ 5.0866],
        [ 2.6908],
        [ 2.4401]])


In [63]:
#init model parameters for log regression
w = torch.normal(0,0.01,size=(2,1),requires_grad=True)
b = torch.zeros(1,requires_grad = True)

In [64]:
def linreg(X,w,b):
    return torch.matmul(X,w)+b

In [65]:
def squared_loss(y_hat,y):
    #print(y_hat.shape)
    #print(y.shape)
    return ((y_hat-y.reshape(y_hat.shape))**2 / 2).sum() #return的时向量

In [66]:
def sgd(params, lr, batch_size):#只是参数更新，参数的梯度在train中求解
    with torch.no_grad():
        for param in params:
            param -= lr* param.grad / batch_size
            param.grad.zero_()

In [69]:
#train
lr = 0.03
num_epochs = 3
net = linreg
loss = squared_loss
for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):
        l = loss(net(X, w, b), y)
        l.backward()
        sgd([w,b], lr, batch_size)
    with torch.no_grad():
        train_l = loss(net(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')

epoch 1, loss 0.048001
epoch 2, loss 0.048096
epoch 3, loss 0.048079


In [68]:
print(f'w的估计误差: {true_w - w.reshape(true_w.shape)}')
print(f'b的估计误差: {true_b - b}')

w的估计误差: tensor([-0.0003, -0.0001], grad_fn=<SubBackward0>)
b的估计误差: tensor([0.0004], grad_fn=<RsubBackward1>)


调用框架中现有的API来读取数据,我们将features和labels作为API的参数传递，并通过数据迭代器指定batch_size。 此外，布尔值is_train表示是否希望数据迭代器对象在每个迭代周期内打乱数据。

In [73]:
from torch.utils import data
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [76]:
next(iter(data_iter))

[tensor([[ 0.7549, -1.9417],
         [-0.1223, -0.5776],
         [-0.0885, -0.0513],
         [ 0.1646,  0.1307],
         [ 1.1810,  0.2983],
         [ 0.6347,  0.6871],
         [ 2.5090,  0.2469],
         [-0.0432,  2.4999],
         [ 0.8507,  0.9372],
         [-0.6377, -1.0521]]),
 tensor([[12.3189],
         [ 5.9289],
         [ 4.2130],
         [ 4.0900],
         [ 5.5520],
         [ 3.1469],
         [ 8.3715],
         [-4.3872],
         [ 2.6908],
         [ 6.5077]])]

 我们首先定义一个模型变量net，它是一个Sequential类的实例。 Sequential类将多个层串联在一起。 当给定输入数据时，Sequential实例将数据传入到第一层， 然后将第一层的输出作为第二层的输入，以此类推。

In [77]:
# nn是神经网络的缩写
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [91]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [92]:
loss = nn.HuberLoss()

In [93]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [94]:
for epoch in range(0,3):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 2.243669
epoch 2, loss 0.371025
epoch 3, loss 0.001101


In [82]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

w的估计误差： tensor([-6.9261e-04, -5.0783e-05])
b的估计误差： tensor([0.0002])


SOFTMAX回归的实现---图像分类 Fashion-MINST

In [4]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms

In [5]:
# 通过ToTensor实例将图像数据从PIL类型变换成32位浮点数格式，
# 并除以255使得所有像素的数值均在0～1之间
trans = transforms.ToTensor()
mnist_train = torchvision.datasets.FashionMNIST(
    root="./data", train=True, transform=trans, download=True)
mnist_test = torchvision.datasets.FashionMNIST(
    root="./data", train=False, transform=trans, download=True)

In [29]:
len(mnist_train), len(mnist_test)

(60000, 10000)

In [30]:
mnist_train[0][0].shape

torch.Size([1, 28, 28])

In [31]:
X, y =next(iter(data.DataLoader(mnist_train, batch_size= 18)))

In [6]:
batch_size = 32
train_iter = data.DataLoader(mnist_train, batch_size, shuffle=True)
test_iter = data.DataLoader(mnist_test, batch_size, shuffle=True)

In [33]:
for X, y in train_iter:
    print(X.shape, X.dtype, y.shape, y.dtype)
    break

torch.Size([32, 1, 28, 28]) torch.float32 torch.Size([32]) torch.int64


In [34]:
trans = [transforms.ToTensor()]
trans.insert(0, transforms.Resize(64))

In [35]:
trans

[Resize(size=64, interpolation=bilinear, max_size=None, antialias=None),
 ToTensor()]

In [9]:
num_inputs = 28*28
num_outputs = 10
W = torch.normal(0, 1, (num_inputs, num_outputs), requires_grad = True)
b = torch.zeros(num_outputs, requires_grad = True)

def softmax(X):
    x_exp = torch.exp(X)
    pa = x_exp.sum(1,keepdim=True)
    return x_exp / pa

def net(X):
    return softmax(torch.matmul(X.reshape(-1, W.shape[0]), W) + b)

def cross_entropy(y_hat, y):
    return -torch.log(y_hat[range(len(y_hat)), y])

def accuracy(y_hat, y):  #@save
    """计算预测正确的数量"""
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = y_hat.argmax(axis=1)
    cmp = y_hat.type(y.dtype) == y
    return float(cmp.type(y.dtype).sum())


class Accumulator:  #@save
    """在n个变量上累加"""
    def __init__(self, n):
        self.data = [0.0] * n

    def add(self, *args):
        self.data = [a + float(b) for a, b in zip(self.data, args)]

    def reset(self):
        self.data = [0.0] * len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

def evaluate_accuracy(net, data_iter):  #@save
    """计算在指定数据集上模型的精度"""
    if isinstance(net, torch.nn.Module):
        net.eval()  # 将模型设置为评估模式
    metric = Accumulator(2)  # 正确预测数、预测总数
    with torch.no_grad():
        for X, y in data_iter:
            metric.add(accuracy(net(X), y), y.numel())
    return metric[0] / metric[1]

In [38]:
evaluate_accuracy(net, test_iter)

0.082

In [62]:
def train(net, train_iter, loss, updater):
    if isinstance(net, torch.nn.Module):
        net.train()
    metric = Accumulator(3)
    for X, y in train_iter:
        y_hat = net(X)
        l = loss(y_hat, y)
        if isinstance(updater, torch.optim.Optimizer):
            updater.zero_grad()
            l.mean().backward()
            updater.step()
        else:
             # 使用定制的优化器和损失函数
            l.sum().backward()
            updater(X.shape[0])
        metric.add(float(l.sum()), accuracy(y_hat, y), y.numel())
    return metric[0] / metric[2], metric[1] / metric[2]

In [42]:
lr = 0.1

def sgd(params, lr, batch_size):#只是参数更新，参数的梯度在train中求解
    with torch.no_grad():
        for param in params:
            param -= lr* param.grad / batch_size
            param.grad.zero_()

def updater(batch_size):
    return sgd([W, b], lr, batch_size)

In [47]:
num_epochs = 10
for i in range(num_epochs):
    print(train(net, train_iter, cross_entropy, updater))

(0.5403624759892622, 0.8344)
(0.5302843319654464, 0.8363166666666667)
(0.523495712463061, 0.8368)
(0.5166626733625929, 0.83745)
(0.5088630161007245, 0.8390666666666666)
(0.5027600609441598, 0.8403)
(0.49703839443326, 0.8407333333333333)
(0.4906820720354716, 0.8432)
(0.48717660724322004, 0.8437166666666667)
(0.47964438350598015, 0.8442333333333333)


In [48]:
def predict(net, test_iter):
    counter = 0
    for X, y in test_iter:
        predict_y = net(X).argmax(axis = 1)
        counter += (predict_y.type(y.dtype) == y).sum()
    return counter/10000

In [49]:
predict(net, test_iter)

tensor(0.8196)

applying softmax in torch

In [11]:
# PyTorch不会隐式地调整输入的形状。因此，
# 我们在线性层前定义了展平层（flatten），来调整网络输入的形状
from torch import nn
import torch
net = nn.Sequential(nn.Flatten(), nn.Linear(784, 10))

def init_weights(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, std=0.01)

net.apply(init_weights);

In [12]:
loss = nn.CrossEntropyLoss(reduction='none')
trainer = torch.optim.SGD(net.parameters(), lr=0.1)
train(net, train_iter, loss, trainer)

(0.5929476642052333, 0.7991666666666667)

In [7]:
def train(net, train_iter, loss, updater):
    if isinstance(net, torch.nn.Module):
        net.train()
    metric = Accumulator(3)
    for X, y in train_iter:
        y_hat = net(X)
        l = loss(y_hat, y)
        if isinstance(updater, torch.optim.Optimizer):
            updater.zero_grad()
            l.mean().backward()
            updater.step()
        else:
             # 使用定制的优化器和损失函数
            l.sum().backward()
            updater(X.shape[0])
        metric.add(float(l.sum()), accuracy(y_hat, y), y.numel())
    return metric[0] / metric[2], metric[1] / metric[2]

计算均方误差使用的是MSELoss类，也称为平方
范数。 默认情况下，它返回所有样本损失的平均值。

从0实现MLP

In [41]:
#model paras define
num_input = 28*28
num_output = 10
num_hidden = 256
W1 = nn.Parameter(torch.randn(
    num_inputs, num_hidden, requires_grad=True) * 0.01)
b1 = nn.Parameter(torch.zeros(num_hidden, requires_grad=True))
W2 = nn.Parameter(torch.randn(
    num_hidden, num_outputs, requires_grad=True) * 0.01)
b2 = nn.Parameter(torch.zeros(num_outputs, requires_grad=True))

params = [W1, b1, W2, b2]

In [42]:
def relu(X):
    a = torch.zeros_like(X)
    return torch.max(X, a)

In [43]:
def net(X):
    X = X.reshape((-1, 28*28))
    H = relu(X@W1 + b1)
    return (H@W2 + b2)

In [37]:
loss = nn.CrossEntropyLoss(reduction='none')

In [45]:
def train(net, train_iter, trainer, loss):
    net.train()
    total = 0
    for X ,y in train_iter:
        trainer.zero_grad()
        y_h = net(X)
        l = loss(y_h ,y)
        total+=l.detach()
        l.mean().backward()
        trainer.step()
    return total.sum() / 10000

In [39]:
#train
num_epoch = 1
trainer = torch.optim.SGD(params, lr= 0.01)
for epoch in range(num_epoch):
    print(train(net, train_iter, trainer, loss))

tensor(6.6092)


In [25]:
def predict(net, test_iter):
    counter = 0
    for X, y in test_iter:
        y_h = net(X).argmax(axis = 1)
        counter+=(y_h.type(y.dtype) == y).sum()
    return counter / 10000

In [26]:
predict(net,test_iter)#100 epoch

tensor(0.8846)

In [33]:
predict(net,test_iter)#10 epoch

tensor(0.8477)

In [44]:
predict(net,test_iter)#1 epoch

tensor(0.1030)

pytorch 实现mlp

In [48]:
net = nn.Sequential(nn.Flatten(),
                    nn.Linear(28*28,256),
                    nn.ReLU(),
                    nn.Linear(256,10))
def init_weights(net):
    if type(net) == nn.Linear:
        nn.init.normal_(net.weight, std=0.01)

net.apply(init_weights)
batch_size, lr, num_epochs = 256, 0.1, 10
loss = nn.CrossEntropyLoss(reduction='none')
trainer = torch.optim.SGD(net.parameters(), lr=lr)
for epoch in range(num_epoch):
    print(train(net, train_iter, trainer, loss))

tensor(3.5453)


In [70]:
loss = nn.MSELoss(reduction='none')#reduction保留长度的loss  删掉变标量输出
for X, y in test_iter:
    loss(net(X).argmax(axis =1), y.type(net(X).dtype))#loss参数dtype设置成float32


模型中防止overfit 添加正则项  e.g. 



In [72]:
def l2_penalty(w):
    return torch.sum(w.pow(2)) / 2


添加惩罚项
```python
l = loss(net(X), y) + lambd * l2_penalty(w)
```

Dropout

In [88]:
def dropout_layer(X, dropout):
    assert 0 <= dropout <= 1
    # 在本情况中，所有元素都被丢弃
    if dropout == 1:
        return torch.zeros_like(X)
    # 在本情况中，所有元素都被保留
    if dropout == 0:
        return X
    mask = (torch.rand(X.shape) > dropout).float()#确定哪些保留，是个bool张量组
    #print("mask:{}".format(mask))
    return mask * X / (1.0 - dropout)

In [80]:
X= torch.arange(16, dtype = torch.float32).reshape((2, 8))
print(X)
print(dropout_layer(X, 0.))
print(dropout_layer(X, 0.5))
print(dropout_layer(X, 1.))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
mask:tensor([[1., 0., 0., 1., 1., 0., 1., 1.],
        [0., 1., 1., 1., 0., 0., 1., 1.]])
tensor([[ 0.,  0.,  0.,  6.,  8.,  0., 12., 14.],
        [ 0., 18., 20., 22.,  0.,  0., 28., 30.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])


带dropout的nn class 

using Fashion-MNIST

In [96]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
# 通过ToTensor实例将图像数据从PIL类型变换成32位浮点数格式，
# 并除以255使得所有像素的数值均在0～1之间
trans = transforms.ToTensor()
mnist_train = torchvision.datasets.FashionMNIST(
    root="./data", train=True, transform=trans, download=True)
mnist_test = torchvision.datasets.FashionMNIST(
    root="./data", train=False, transform=trans, download=True)
batch_size = 256
train_iter = data.DataLoader(mnist_train, batch_size, shuffle=True)
test_iter = data.DataLoader(mnist_test, batch_size, shuffle=True)

In [90]:
num_inputs, num_outputs, num_hiddens1, num_hiddens2 = 784, 10, 256, 256

In [91]:
dropout1, dropout2 = 0.2, 0.5
class Net(nn.Module):
    def __init__(self, num_inputs, num_outputs, num_hiddens1, num_hiddens2, 
                 is_training = True):
        super(Net,self).__init__()
        self.num_inputs = num_inputs
        self.is_training = is_training
        self.lin1 = nn.Linear(num_inputs, num_hiddens1)
        self.lin2 = nn.Linear(num_hiddens1, num_hiddens2)
        self.lin3 = nn.Linear(num_hiddens2, num_outputs)
        self.relu = nn.ReLU()
        
    def forward(self, X):
        H1 = self.relu(self.lin1(X.reshape((-1,num_inputs))))
        if self.is_training:
            H1 = dropout_layer(H1,dropout1)
        H2 = self.lin2(H1)
        H2 = self.relu(H2)
        if self.is_training:
            H2 = dropout_layer(H2, dropout2)
        out = self.lin3(H2)
        return out
net = Net(num_inputs, num_outputs, num_hiddens1, num_hiddens2)

In [93]:
def train(net, train_iter, trainer, loss):
    total = 0
    for X, y in train_iter:
        trainer.zero_grad()
        y_h = net(X)
        l = loss(y_h , y)
        l.backward()
        trainer.step()
        total+=l
    print(total)
trainer = torch.optim.SGD(net.parameters(), lr=0.1)
loss = nn.CrossEntropyLoss()
num_epoch = 3
for i in range(num_epoch):
    train(net,train_iter,trainer, loss)

tensor(713.7004, grad_fn=<AddBackward0>)
tensor(686.5836, grad_fn=<AddBackward0>)
tensor(653.1824, grad_fn=<AddBackward0>)


利用torch的dropout API

In [95]:
net = nn.Sequential(nn.Flatten(),
                   nn.Linear(784,256),
                   nn.ReLU(),
                   nn.Dropout(dropout1),
                   nn.Linear(256,256),
                   nn.ReLU(),
                   nn.Dropout(dropout2),
                   nn.Linear(256,10))
def init_weights(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, std=0.01)
net.apply(init_weights)
trainer = torch.optim.SGD(net.parameters(), lr=0.1)
loss = nn.CrossEntropyLoss()
for i in range(num_epoch):
    train(net,train_iter,trainer, loss)

tensor(1509.4799, grad_fn=<AddBackward0>)
tensor(877.6586, grad_fn=<AddBackward0>)
tensor(787.2360, grad_fn=<AddBackward0>)


init of torch model using pytorch API

definition of block and layer in torch

In [1]:
import torch
from torch import nn
from torch.nn import functional as F


class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.relu = nn.ReLU()
        self.out = nn.Linear(256,10)
        
    def forward(self,X):
        X = self.hidden(X)
        X = self.relu(X)
        X = self.out(X)
        return X

In [2]:
X = torch.rand(2, 20)
net = MLP()
net(X)

tensor([[-0.0559, -0.0347, -0.1690,  0.2290, -0.1363,  0.2795,  0.0493, -0.0890,
         -0.0780, -0.1963],
        [-0.0163,  0.0552, -0.1340,  0.2768, -0.0757,  0.0831,  0.0403, -0.0269,
         -0.1196, -0.1323]], grad_fn=<AddmmBackward0>)

In [10]:
class seq(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for idx, module in enumerate(args):
            self._modules[str(idx)] = module
            print(type(self._modules))
            print(self._modules.values())
    
    def forward(self, X):
        for block in self._modules.values():
            print(block)
            X = block(X)
        return X

## addition: (*args, **kargs)

In [7]:
def myfun(*args):
    print(type(args))
    print("参数个数",len(args))
    print("第一个参数:",args[0])
    print("第二个参数:",args[1])
 
  
myfun(10, "我可以", [1,2])

<class 'tuple'>
参数个数 3
第一个参数: 10
第二个参数: 我可以


可以看到我这里只输出了2个我传入的两个参数，如果我只传入1个参数，那么在代码的第5行将会报错，因为args元组中参数个数只有1个，无法提取args[1]。这就是函数定义时*args的用法，当然该用法也可以和指定参数一起使用，例如我在定义函数的时候def myfun(arg1, arg2, *args)，那么这个时候传入参数的第一个参数会认为arg1，第二个参数时arg2，第三个即以后的传入的参数会被args当成元组组合

In [8]:
def myfun(**kargs):
    print(type(kargs))
    print("参数个数",len(kargs))
    print("字典具有那些键？",kargs.keys())
    ## 打印kargs的所有项
    for item in kargs.items():
        print("item:",item)
 
  
myfun(number=10, number2=['可以1','可以2'])

<class 'dict'>
参数个数 2
字典具有那些键？ dict_keys(['number', 'number2'])
item: ('number', 10)
item: ('number2', ['可以1', '可以2'])


In [9]:
def myfun(number, **kargs):
    print("参数number:",number)
    print(type(kargs))
    print("参数个数",len(kargs))
    print("字典具有那些键？",kargs.keys())
    ## 打印kargs的所有项
    for item in kargs.items():
        print("item:",item)
 
  
myfun(number=10, number2=['可以1','可以2'])

参数number: 10
<class 'dict'>
参数个数 1
字典具有那些键？ dict_keys(['number2'])
item: ('number2', ['可以1', '可以2'])


情况解释同 *args

## in function use

在使用函数的时候，我们可以通过 * 元组(列表)的方式把元组(列表)中所有的元素传入进函数里。要注意args一定要是元组(列表)，并且args的个数一定要和函数需要的参数个数一样多。

In [12]:
def myfun(arg1, arg2, arg3):
    print("参数arg1:",arg1)
    print("参数arg2:",arg2)
    print("参数arg3:",arg3)
args = (1,2,3)
myfun(*args)

参数arg1: 1
参数arg2: 2
参数arg3: 3


同样的我们使用**kargs可以把一个字典传入函数，但是要注意的是这个字典的键(str)必须得和函数定义时的参数名对应。

In [13]:
def myfun(arg1, arg2, arg3):
    print("参数arg1:",arg1)
    print("参数arg2:",arg2)
    print("参数arg3:",arg3)

kargs = {'arg1':1, 'arg2':2, 'arg3':"可以"}
myfun(**kargs)

参数arg1: 1
参数arg2: 2
参数arg3: 可以


In [11]:
net = seq(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))
net(X)

<class 'collections.OrderedDict'>
odict_values([Linear(in_features=20, out_features=256, bias=True)])
<class 'collections.OrderedDict'>
odict_values([Linear(in_features=20, out_features=256, bias=True), ReLU()])
<class 'collections.OrderedDict'>
odict_values([Linear(in_features=20, out_features=256, bias=True), ReLU(), Linear(in_features=256, out_features=10, bias=True)])
Linear(in_features=20, out_features=256, bias=True)
ReLU()
Linear(in_features=256, out_features=10, bias=True)


tensor([[ 0.1064, -0.1988, -0.0105, -0.1310,  0.1192,  0.0721,  0.2253, -0.0141,
         -0.0704,  0.0939],
        [ 0.1507, -0.0456, -0.0243, -0.0710,  0.1451,  0.0653,  0.1805, -0.0570,
         -0.1050,  0.0041]], grad_fn=<AddmmBackward0>)

# add const para in layers

FixedHiddenMLP类

有一个 $20*20$ 的 hidden layer 其参数不会被更新

In [12]:
class FixedHiddenMLP(nn.Module):
    def __init__(self):
        super().__init__()
        # 不计算梯度的随机权重参数。因此其在训练期间保持不变
        self.rand_weight = torch.rand((20, 20), requires_grad=False)
        self.linear = nn.Linear(20, 20)

    def forward(self, X):
        X = self.linear(X)
        # 使用创建的常量参数以及relu和mm函数
        X = F.relu(torch.mm(X, self.rand_weight) + 1)
        # 复用全连接层。这相当于两个全连接层共享参数
        X = self.linear(X)
        # 控制流
        while X.abs().sum() > 1:
            X /= 2
        return X.sum()

In [13]:
net = FixedHiddenMLP()
net(X)

tensor(-0.1004, grad_fn=<SumBackward0>)

In [14]:
#seq方法和block方法混用实现nestNN
class NestMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(20, 64), nn.ReLU(),
                                 nn.Linear(64, 32), nn.ReLU())
        self.linear = nn.Linear(32, 16)

    def forward(self, X):
        return self.linear(self.net(X))

chimera = nn.Sequential(NestMLP(), nn.Linear(16, 20), FixedHiddenMLP())
chimera(X)

tensor(0.0170, grad_fn=<SumBackward0>)

In [1]:
import torch
from torch import nn

#parameters in a torch sequential instance
net = nn.Sequential(nn.Linear(4,8),
                   nn.ReLU(),
                   nn.Linear(8,1))

X = torch.rand((2,4))
net(X)

tensor([[0.0722],
        [0.0949]], grad_fn=<AddmmBackward0>)

In [2]:
print(net[2].state_dict())

OrderedDict([('weight', tensor([[-0.0379, -0.0591, -0.1122,  0.2944, -0.1315,  0.2350, -0.2537, -0.0678]])), ('bias', tensor([0.2445]))])


In [4]:
print(type(net[2].bias))
print(net[2].bias)
print("\n")
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([0.2445], requires_grad=True)


tensor([0.2445])


除了值之外，我们还可以访问每个参数的梯度。 在上面这个网络中，由于我们还没有调用反向传播，所以参数的梯度处于初始状态。

In [5]:
net[2].weight.grad == None

True

In [25]:
print([(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net[0].named_parameters()][0])
print(*[(name, param.shape) for name, param in net.named_parameters()])
#use of * represents extract each element of the array with unknown length 具体解释见上 addition 

[('weight', torch.Size([8, 4])), ('bias', torch.Size([8]))]
weight torch.Size([8, 4])
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [14]:
net.state_dict()['2.bias'].data

tensor([0.2445])

嵌套block的组合

In [15]:
def block1():
    return nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                         nn.Linear(8, 4), nn.ReLU())

def block2():
    net = nn.Sequential()
    for i in range(4):
        # 在这里嵌套
        net.add_module(f'block {i}', block1())
    return net

rgnet = nn.Sequential(block2(), nn.Linear(4, 1))
rgnet(X)

print(rgnet)

Sequential(
  (0): Sequential(
    (block 0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [16]:
rgnet[0][1][0].bias.data

tensor([-0.0032,  0.2150, -0.1579,  0.3901,  0.4466,  0.0830, -0.2737,  0.2242])

# init the parameters

In [17]:
def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, mean=0, std=0.01)
        nn.init.zeros_(m.bias)
net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([ 0.0232, -0.0095,  0.0010,  0.0124]), tensor(0.))

In [18]:
def init_constant(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 1)
        nn.init.zeros_(m.bias)
net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [19]:
def init_xavier(m):
    if type(m) == nn.Linear:
        nn.init.xavier_uniform_(m.weight)
def init_42(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight, 42)

net[0].apply(init_xavier)
net[2].apply(init_42)
print(net[0].weight.data[0])
print(net[2].weight.data)

tensor([-0.1628, -0.6258,  0.5600,  0.5350])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])


In [20]:
#net.named_parameters() -> ('0.bias', torch.Size([8]))
def my_init(m):
    if type(m) == nn.Linear:
        print("Init", *[(name, param.shape)
                        for name, param in m.named_parameters()][0])
        nn.init.uniform_(m.weight, -10, 10)
        m.weight.data *= m.weight.data.abs() >= 5

net.apply(my_init)
net[0].weight[:2]

Init weight torch.Size([8, 4])
Init weight torch.Size([1, 8])


tensor([[ 7.1471,  8.2622, -0.0000, -9.5419],
        [ 0.0000, -0.0000, -8.2057,  0.0000]], grad_fn=<SliceBackward0>)

In [26]:
net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 42
net[0].weight.data[0]

tensor([42.0000,  9.2622,  1.0000, -8.5419])

# 共享参数&参数绑定

benefits：
共享参数通常可以节省内存，并在以下方面具有特定的好处：

对于图像识别中的CNN，共享参数使网络能够在图像中的任何地方而不是仅在某个区域中查找给定的功能。

对于RNN，它在序列的各个时间步之间共享参数，因此可以很好地推广到不同序列长度的示例。

对于自动编码器，编码器和解码器共享参数。 在具有线性激活的单层自动编码器中，共享权重会在权重矩阵的不同隐藏层之间强制正交forces orthogonality。

In [27]:
# 我们需要给共享层一个名称，以便可以引用它的参数
shared = nn.Linear(8, 8)
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.Linear(8, 1))
net(X)
# 检查参数是否相同
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = 100
# 确保它们实际上是同一个对象，而不只是有相同的值
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])


In [5]:
import torch
torch.randn(10,2)

tensor([[ 1.3226, -0.4290],
        [ 1.3846, -0.8769],
        [-0.2620, -0.4138],
        [ 0.0865, -1.1723],
        [ 0.4146,  0.4091],
        [ 0.1941, -0.6885],
        [-0.3985,  0.0267],
        [ 0.4931,  0.8588],
        [-2.0917,  0.6129],
        [ 1.1806,  0.5261]])

# CNN realization

In [2]:
import torch
from torch import nn
# 卷积->互相关运算
def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

In [8]:
X[0:2,0:2] *K

tensor([[ 0.,  1.],
        [ 6., 12.]])

In [39]:
class cov2d(nn.Module):
    def __init__(self):
        super().__init__()
        self.kernel = nn.Parameter(torch.randn((1,2)))
        self.bias = nn.Parameter(torch.zeros(1))
        
    def forward(self, x):
        return corr2d(x,self.kernel)+self.bias

In [3]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
X
K = torch.tensor([[1.0, -1.0]])
Y = corr2d(X, K)
Y


tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [4]:
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [5]:
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [47]:
net = cov2d()
opt = torch.optim.SGD(net.parameters(),lr=3e-3)
for i in range(1000):
    y_h=net(X)
    l=(y_h-Y)**2
    opt.zero_grad()
    l.sum().backward()
    opt.step()
    print(net.kernel)
    print(net.bias)
    print(y_h)

Parameter containing:
tensor([[-1.2818,  0.8158]], requires_grad=True)
Parameter containing:
tensor([0.0614], requires_grad=True)
tensor([[-0.5683, -1.4095,  0.0000,  0.0000,  0.0000,  0.8411, -0.5683],
        [-0.5683, -1.4095,  0.0000,  0.0000,  0.0000,  0.8411, -0.5683],
        [-0.5683, -1.4095,  0.0000,  0.0000,  0.0000,  0.8411, -0.5683],
        [-0.5683, -1.4095,  0.0000,  0.0000,  0.0000,  0.8411, -0.5683],
        [-0.5683, -1.4095,  0.0000,  0.0000,  0.0000,  0.8411, -0.5683],
        [-0.5683, -1.4095,  0.0000,  0.0000,  0.0000,  0.8411, -0.5683]],
       grad_fn=<AddBackward0>)
Parameter containing:
tensor([[-1.1727,  0.7773]], requires_grad=True)
Parameter containing:
tensor([0.0962], requires_grad=True)
tensor([[-0.4047, -1.2204,  0.0614,  0.0614,  0.0614,  0.8771, -0.4047],
        [-0.4047, -1.2204,  0.0614,  0.0614,  0.0614,  0.8771, -0.4047],
        [-0.4047, -1.2204,  0.0614,  0.0614,  0.0614,  0.8771, -0.4047],
        [-0.4047, -1.2204,  0.0614,  0.0614,  0.061

Parameter containing:
tensor([0.0020], requires_grad=True)
tensor([[-0.0017,  0.8593,  0.0022,  0.0022,  0.0022, -0.8588, -0.0017],
        [-0.0017,  0.8593,  0.0022,  0.0022,  0.0022, -0.8588, -0.0017],
        [-0.0017,  0.8593,  0.0022,  0.0022,  0.0022, -0.8588, -0.0017],
        [-0.0017,  0.8593,  0.0022,  0.0022,  0.0022, -0.8588, -0.0017],
        [-0.0017,  0.8593,  0.0022,  0.0022,  0.0022, -0.8588, -0.0017],
        [-0.0017,  0.8593,  0.0022,  0.0022,  0.0022, -0.8588, -0.0017]],
       grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 0.8673, -0.8707]], requires_grad=True)
Parameter containing:
tensor([0.0019], requires_grad=True)
tensor([[-0.0016,  0.8643,  0.0020,  0.0020,  0.0020, -0.8639, -0.0016],
        [-0.0016,  0.8643,  0.0020,  0.0020,  0.0020, -0.8639, -0.0016],
        [-0.0016,  0.8643,  0.0020,  0.0020,  0.0020, -0.8639, -0.0016],
        [-0.0016,  0.8643,  0.0020,  0.0020,  0.0020, -0.8639, -0.0016],
        [-0.0016,  0.8643,  0.0020,  0.0020,  0.0

Parameter containing:
tensor([2.6954e-05], requires_grad=True)
tensor([[-2.2561e-05,  9.8957e-01,  2.8639e-05,  2.8639e-05,  2.8639e-05,
         -9.8956e-01, -2.2561e-05],
        [-2.2561e-05,  9.8957e-01,  2.8639e-05,  2.8639e-05,  2.8639e-05,
         -9.8956e-01, -2.2561e-05],
        [-2.2561e-05,  9.8957e-01,  2.8639e-05,  2.8639e-05,  2.8639e-05,
         -9.8956e-01, -2.2561e-05],
        [-2.2561e-05,  9.8957e-01,  2.8639e-05,  2.8639e-05,  2.8639e-05,
         -9.8956e-01, -2.2561e-05],
        [-2.2561e-05,  9.8957e-01,  2.8639e-05,  2.8639e-05,  2.8639e-05,
         -9.8956e-01, -2.2561e-05],
        [-2.2561e-05,  9.8957e-01,  2.8639e-05,  2.8639e-05,  2.8639e-05,
         -9.8956e-01, -2.2561e-05]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 0.9903, -0.9903]], requires_grad=True)
Parameter containing:
tensor([2.5370e-05], requires_grad=True)
tensor([[-2.1266e-05,  9.8994e-01,  2.6954e-05,  2.6954e-05,  2.6954e-05,
         -9.8994e-01, -2.1266e-05],
        

Parameter containing:
tensor([3.5060e-07], requires_grad=True)
tensor([[-2.8304e-07,  9.9926e-01,  3.7261e-07,  3.7261e-07,  3.7261e-07,
         -9.9926e-01, -2.8304e-07],
        [-2.8304e-07,  9.9926e-01,  3.7261e-07,  3.7261e-07,  3.7261e-07,
         -9.9926e-01, -2.8304e-07],
        [-2.8304e-07,  9.9926e-01,  3.7261e-07,  3.7261e-07,  3.7261e-07,
         -9.9926e-01, -2.8304e-07],
        [-2.8304e-07,  9.9926e-01,  3.7261e-07,  3.7261e-07,  3.7261e-07,
         -9.9926e-01, -2.8304e-07],
        [-2.8304e-07,  9.9926e-01,  3.7261e-07,  3.7261e-07,  3.7261e-07,
         -9.9926e-01, -2.8304e-07],
        [-2.8304e-07,  9.9926e-01,  3.7261e-07,  3.7261e-07,  3.7261e-07,
         -9.9926e-01, -2.8304e-07]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 0.9993, -0.9993]], requires_grad=True)
Parameter containing:
tensor([3.3256e-07], requires_grad=True)
tensor([[-3.0505e-07,  9.9928e-01,  3.5060e-07,  3.5060e-07,  3.5060e-07,
         -9.9928e-01, -3.0505e-07],
        

Parameter containing:
tensor([3.0776e-08], requires_grad=True)
tensor([[-2.9924e-08,  9.9994e-01,  2.9681e-08,  2.9681e-08,  2.9681e-08,
         -9.9994e-01, -2.9924e-08],
        [-2.9924e-08,  9.9994e-01,  2.9681e-08,  2.9681e-08,  2.9681e-08,
         -9.9994e-01, -2.9924e-08],
        [-2.9924e-08,  9.9994e-01,  2.9681e-08,  2.9681e-08,  2.9681e-08,
         -9.9994e-01, -2.9924e-08],
        [-2.9924e-08,  9.9994e-01,  2.9681e-08,  2.9681e-08,  2.9681e-08,
         -9.9994e-01, -2.9924e-08],
        [-2.9924e-08,  9.9994e-01,  2.9681e-08,  2.9681e-08,  2.9681e-08,
         -9.9994e-01, -2.9924e-08],
        [-2.9924e-08,  9.9994e-01,  2.9681e-08,  2.9681e-08,  2.9681e-08,
         -9.9994e-01, -2.9924e-08]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 0.9999, -0.9999]], requires_grad=True)
Parameter containing:
tensor([2.7382e-08], requires_grad=True)
tensor([[-2.8829e-08,  9.9994e-01,  3.0776e-08,  3.0776e-08,  3.0776e-08,
         -9.9994e-01, -2.8829e-08],
        

Parameter containing:
tensor([6.3405e-14], requires_grad=True)
tensor([[ 7.7047e-14,  1.0000e+00,  7.7047e-14,  7.7047e-14,  7.7047e-14,
         -1.0000e+00,  7.7047e-14],
        [ 7.7047e-14,  1.0000e+00,  7.7047e-14,  7.7047e-14,  7.7047e-14,
         -1.0000e+00,  7.7047e-14],
        [ 7.7047e-14,  1.0000e+00,  7.7047e-14,  7.7047e-14,  7.7047e-14,
         -1.0000e+00,  7.7047e-14],
        [ 7.7047e-14,  1.0000e+00,  7.7047e-14,  7.7047e-14,  7.7047e-14,
         -1.0000e+00,  7.7047e-14],
        [ 7.7047e-14,  1.0000e+00,  7.7047e-14,  7.7047e-14,  7.7047e-14,
         -1.0000e+00,  7.7047e-14],
        [ 7.7047e-14,  1.0000e+00,  7.7047e-14,  7.7047e-14,  7.7047e-14,
         -1.0000e+00,  7.7047e-14]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([6.3405e-14], requires_grad=True)
tensor([[ 6.3405e-14,  1.0000e+00,  6.3405e-14,  6.3405e-14,  6.3405e-14,
         -1.0000e+00,  6.3405e-14],
        

Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,

Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        

tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-1

Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        

Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        

Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,

Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        

Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        

Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        [ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15]], grad_fn=<AddBackward0>)
Parameter containing:
tensor([[ 1.0000, -1.0000]], requires_grad=True)
Parameter containing:
tensor([8.1531e-15], requires_grad=True)
tensor([[ 8.1531e-15,  1.0000e+00,  8.1531e-15,  8.1531e-15,  8.1531e-15,
         -1.0000e+00,  8.1531e-15],
        

In [10]:
# 构造一个二维卷积层，它具有1个输入通道1个输出通道和形状为（1，2）的卷积核

conv2d = nn.Conv2d(1,1, kernel_size=(1, 2), bias=False)

# 这个二维卷积层使用四维输入和输出格式（批量大小、通道、高度、宽度），
# 其中批量大小和通道数都为1
X = X.reshape((1, 1, 6, 8))
Y = Y.reshape((1, 1, 6, 7))
lr = 3e-2  # 学习率

for i in range(10):
    Y_hat = conv2d(X)
    l = (Y_hat - Y) ** 2
    conv2d.zero_grad()
    l.sum().backward()
    # 迭代卷积核
    conv2d.weight.data[:] -= lr * conv2d.weight.grad
    if (i + 1) % 2 == 0:
        print(f'epoch {i+1}, loss {l.sum():.3f}')

epoch 2, loss 5.716
epoch 4, loss 1.028
epoch 6, loss 0.201
epoch 8, loss 0.045
epoch 10, loss 0.012


In [11]:
X

tensor([[[[1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.],
          [1., 1., 0., 0., 0., 0., 1., 1.]]]])

使用奇数的核大小和填充大小也提供了书写上的便利。对于任何二维张量X，

当满足：

1. 卷积核的大小是奇数；

2. 所有边的填充行数和列数相同；

3. 输出与输入具有相同高度和宽度 则可以得出：输出Y[i, j]是通过以输入X[i, j]为中心，与卷积核进行互相关计算得到的。

In [18]:
#带padding的conv层

def comp_conv(conv2d, X):
    #（1，1）表示批量大小和通道数都是1
    X= X.reshape((1,1)+X.shape)
    Y= conv2d(X)
    return Y.reshape(Y.shape[2:])
# 请注意，这里每边都填充了1行或1列，因此总共添加了2行或2列
conv2d = nn.Conv2d(1,1,kernel_size=3,padding=1)#padding参数可以是元组，第0维度表示高度填充，第一维度表示宽度填充
X = torch.rand(size=(8,8))
comp_conv(conv2d,X).shape

torch.Size([8, 8])

# conv with stride
如果我们设置了$p_h=k_h-1$
和$p_w=k_w-1$
，则输出形状将简化为$\lfloor(n_h+s_h-1)/s_h\rfloor \times \lfloor(n_w+s_w-1)/s_w\rfloor$
。 更进一步，如果输入的高度和宽度可以被垂直和水平步幅整除，则输出形状将为$(n_h/s_h) \times (n_w/s_w)$
。

注意这里的padding是在行和列总的padding数,而在代码实现中，padding的值是在每条边都进行的padding数，注意区分一个1/2的关系

总的公式$\frac{N-F+2P}{S}+1$这里的p与代码中的p的意义相同，上下各padding p 行 F是kernel size

In [20]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)
comp_conv(conv2d, X).shape

torch.Size([4, 4])

# 多输入输出通道


In [21]:
def multi_channel_conv(X,K,cov2d):
    return sum(cov2d(x,k) for x,k in zip(X,K))

In [41]:
def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

multi_channel_conv(X, K,corr2d)

tensor([[ 56.,  72.],
        [104., 120.]])

In [42]:
X.shape #=>torch.Size([2, 3, 3])
list(zip(X,K))

[(tensor([[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]),
  tensor([[0., 1.],
          [2., 3.]])),
 (tensor([[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]),
  tensor([[1., 2.],
          [3., 4.]]))]

In [58]:
#多输出通道
def multi_out_channel(X,K,cov2d):
    return torch.stack([multi_channel_conv(X,k,cov2d)for k in K],0)

X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])
K = torch.stack((K, K + 1, K + 2), 0)
print(K.shape)
multi_out_channel(X, K,corr2d)

torch.Size([3, 2, 2, 2])


tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

# 1*1 conv

In [48]:
#在通道维度进行计算

#输出图像同一位置通道的线性和 改变out channel实现降维等操作

#等价
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    # 全连接层中的矩阵乘法
    Y = torch.matmul(K, X)
    return Y.reshape((c_o, h, w))

def multi_channel_conv_1x1(X,K,cov2d):
    #X->input image dim = (input channel, height, width)
    #in_channel, h, w = X.shape
    #out_channel, k_h, k_w = K.shape
    return torch.stack([multi_channel_conv(X,k,cov2d) for k in K],0)

In [59]:
X = torch.normal(0, 1, (3, 3, 3))
#X.shape -> 3dim inputchannel image height image width
K = torch.normal(0, 1, (2, 3, 1, 1))
# K.shape ->4 dim outchannel, inputchannel height width
Y1 = multi_channel_conv_1x1(X, K,corr2d)
Y2 = multi_out_channel(X, K,corr2d)
assert float(torch.abs(Y1 - Y2).sum()) < 1e-6
Y1

tensor([[[ 0.5843, -0.6282, -0.9563],
         [-2.6099, -0.7569, -0.3381],
         [ 0.7956,  1.9331,  0.5436]],

        [[ 0.5965,  1.4130,  0.8556],
         [ 3.9786, -0.4743,  0.3217],
         [-1.4813, -3.4925, -0.5344]]])

In [54]:
X

tensor([[[-0.5190, -1.5707, -0.6223],
         [-1.8171, -1.7568, -0.0597],
         [-0.5616,  1.7273, -2.9090]],

        [[-1.1778, -2.4448,  2.0372],
         [-0.5066,  0.0812,  0.9956],
         [ 0.4726,  0.3324, -0.5757]],

        [[-0.2781,  1.7011, -0.0561],
         [ 0.7277, -2.4823, -0.5242],
         [-0.3679, -0.9669,  0.9649]]])

In [57]:
K

tensor([[[[ 0.8568]],

         [[ 0.1840]],

         [[ 0.6382]]],


        [[[-1.3442]],

         [[ 0.0525]],

         [[ 1.4668]]]])

# pooling conv
本节将介绍汇聚（pooling）层，它具有双重目的：降低卷积层对位置的敏感性，同时降低对空间降采样表示的敏感性。

In [68]:
#max pooling
def pool2d(X,pool_size,method = 'max'):
    pw,ph = pool_size
    res = torch.zeros((X.shape[0]-ph+1,X.shape[1] - pw+1))
    for x in range(res.shape[0]):
        for y in range(res.shape[1]):
            if method == 'max':
                res[x,y] = X[x:x+ph,y:y+pw].max()
            else:
                res[x,y] = X[x:x+ph,y:y+pw].mean()
    return res


In [69]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [70]:
#padding & stride
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [75]:
#如果我们使用形状为(3, 3)的汇聚窗口，那么默认情况下，我们得到的步幅(stride)形状为(3, 3)。
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [76]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [77]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [79]:
#multi channel pooling
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
#X dim -> 样本数 通道数 height width
#增加一个通道
X = torch.cat((X,X+1),1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [80]:
#multi channel pooling
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X) #channel -> same to X channel

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

In [89]:
#practice -> LeNet-5
class Lenet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5, padding=2)
        self.pool1 = nn.AvgPool2d(2)
        self.conv2 = nn.Conv2d(6, 16, kernel_size= 5)
        self.sigmoid = nn.Sigmoid()
        self.pool2 = nn.AvgPool2d(2)
        self.flatten = nn.Flatten()
        self.mlp = nn.Sequential(
            nn.Linear(16*25,120),
            nn.Sigmoid(),
            nn.Linear(120,84),
            nn.Sigmoid(),
            nn.Linear(84,10)
        )
        
    def forward(self,X):
        X = self.conv1(X)
        X = self.sigmoid(X)
        X = self.pool1(X)
        X = self.conv2(X)
        X = self.sigmoid(X)
        X = self.pool2(X)
        X = self.flatten(X)
        X = self.mlp(X)
        return X
        
    

In [94]:
net = Lenet()
X=torch.rand(size=(5, 1, 28, 28), dtype=torch.float32)#dim->样本数 每个样本input channel height*width
net(X)

tensor([[-0.8640,  0.2646,  0.0881, -0.1031,  0.1028,  0.2124, -0.0712,  0.0794,
          0.0934,  0.0477],
        [-0.8640,  0.2647,  0.0882, -0.1031,  0.1028,  0.2124, -0.0712,  0.0795,
          0.0934,  0.0477],
        [-0.8640,  0.2646,  0.0882, -0.1031,  0.1027,  0.2124, -0.0712,  0.0794,
          0.0934,  0.0477],
        [-0.8640,  0.2647,  0.0882, -0.1031,  0.1028,  0.2124, -0.0712,  0.0794,
          0.0933,  0.0477],
        [-0.8640,  0.2647,  0.0882, -0.1031,  0.1028,  0.2124, -0.0712,  0.0794,
          0.0934,  0.0477]], grad_fn=<AddmmBackward0>)

In [115]:
def init_weights(m):
        if type(m) == nn.Linear or type(m) == nn.Conv2d:
            nn.init.xavier_uniform_(m.weight)
net.apply(init_weights)

Lenet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (pool1): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (sigmoid): Sigmoid()
  (pool2): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (mlp): Sequential(
    (0): Linear(in_features=400, out_features=120, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=120, out_features=84, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=84, out_features=10, bias=True)
  )
)

In [116]:
device = 'cuda:0'
net.to(device)

Lenet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (pool1): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (sigmoid): Sigmoid()
  (pool2): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (mlp): Sequential(
    (0): Linear(in_features=400, out_features=120, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=120, out_features=84, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=84, out_features=10, bias=True)
  )
)

In [118]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
# 通过ToTensor实例将图像数据从PIL类型变换成32位浮点数格式，
# 并除以255使得所有像素的数值均在0～1之间
trans = [transforms.ToTensor()]
trans = transforms.Compose(trans)
mnist_train = torchvision.datasets.FashionMNIST(
    root="./data", train=True, transform=trans, download=True)
mnist_test = torchvision.datasets.FashionMNIST(
    root="./data", train=False, transform=trans, download=True)
batch_size = 256
train_iter = data.DataLoader(mnist_train, batch_size, shuffle=True)
test_iter = data.DataLoader(mnist_test, batch_size, shuffle=True)

In [131]:
def train(net,opt,loss,num_epoch,train_iter,test_iter,device):
    net.to(device)
    for epoch in range(num_epoch):
        net.train()
        for i, (X,y) in enumerate(train_iter):
            opt.zero_grad()
            X, y  = X.to(device),y.to(device)
            y_pred = net(X)
            l = loss(y_pred,y)
            l.backward()
            opt.step()
        with torch.no_grad():
            net.eval()
            testloss = 0
            truenum = 0
            tit = 0
            for p, (tx,ty) in enumerate(test_iter):
                tx,ty = tx.to(device), ty.to(device)
                y_p = net(tx)
                testloss+=loss(y_p,ty)
                #print(torch.argmax(y_p,axis =1))
                #print(ty)
                tit+=y_p.shape[0]
                truenum += (torch.argmax(y_p,axis = 1) == ty).sum()
        print("epoch: {}, test loss = {},ture item={}".format(epoch,testloss,truenum/tit))

                    
opt = torch.optim.SGD(net.parameters(),lr = 0.9)
loss = nn.CrossEntropyLoss()
train(net,opt,loss,10,train_iter,test_iter,device)
            

epoch: 0, test loss = 13.4820556640625,ture item=0.877299964427948
epoch: 1, test loss = 15.362674713134766,ture item=0.8565999865531921
epoch: 2, test loss = 12.245208740234375,ture item=0.8822999596595764
epoch: 3, test loss = 13.128581047058105,ture item=0.8747999668121338
epoch: 4, test loss = 13.039472579956055,ture item=0.8765999674797058
epoch: 5, test loss = 12.756024360656738,ture item=0.8845999836921692
epoch: 6, test loss = 12.011873245239258,ture item=0.8888999819755554
epoch: 7, test loss = 13.034342765808105,ture item=0.8811999559402466
epoch: 8, test loss = 11.777715682983398,ture item=0.8938999772071838
epoch: 9, test loss = 13.391213417053223,ture item=0.8752999901771545


# 现代卷积神经网络 alexnet  vgg nin googlenet resnet densenet


In [7]:
#Alexnet
import torch
from torch import nn

#def of alexnet
net  = nn.Sequential(
    nn.Conv2d(1,96,kernel_size=11,stride=4),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=3,stride=2),
    nn.Conv2d(96,256,kernel_size=5,padding=2),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=3,stride = 2),
    nn.Conv2d(256,384,kernel_size=3,padding=1),
    nn.ReLU(),
    nn.Conv2d(384,384,kernel_size=3,padding=1),
    nn.ReLU(),
    nn.Conv2d(384,256,kernel_size=3,padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=3,stride=2),
    nn.Flatten(),
    nn.Linear(6400, 4096), nn.ReLU(),
    nn.Dropout(p=0.5),
    nn.Linear(4096, 4096), nn.ReLU(),
    nn.Dropout(p=0.5),
    # 最后是输出层。由于这里使用Fashion-MNIST，所以用类别数为10，而非论文中的1000
    nn.Linear(4096, 10)    
)

In [8]:
X = torch.randn(2, 1, 224, 224)
for layer in net:
    X=layer(X)
    print(layer.__class__.__name__,'output shape:\t',X.shape)

Conv2d output shape:	 torch.Size([2, 96, 54, 54])
ReLU output shape:	 torch.Size([2, 96, 54, 54])
MaxPool2d output shape:	 torch.Size([2, 96, 26, 26])
Conv2d output shape:	 torch.Size([2, 256, 26, 26])
ReLU output shape:	 torch.Size([2, 256, 26, 26])
MaxPool2d output shape:	 torch.Size([2, 256, 12, 12])
Conv2d output shape:	 torch.Size([2, 384, 12, 12])
ReLU output shape:	 torch.Size([2, 384, 12, 12])
Conv2d output shape:	 torch.Size([2, 384, 12, 12])
ReLU output shape:	 torch.Size([2, 384, 12, 12])
Conv2d output shape:	 torch.Size([2, 256, 12, 12])
ReLU output shape:	 torch.Size([2, 256, 12, 12])
MaxPool2d output shape:	 torch.Size([2, 256, 5, 5])
Flatten output shape:	 torch.Size([2, 6400])
Linear output shape:	 torch.Size([2, 4096])
ReLU output shape:	 torch.Size([2, 4096])
Dropout output shape:	 torch.Size([2, 4096])
Linear output shape:	 torch.Size([2, 4096])
ReLU output shape:	 torch.Size([2, 4096])
Dropout output shape:	 torch.Size([2, 4096])
Linear output shape:	 torch.Size([2,

In [7]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
# 通过ToTensor实例将图像数据从PIL类型变换成32位浮点数格式，
# 并除以255使得所有像素的数值均在0～1之间
trans = [transforms.ToTensor()]
trans.insert(0, transforms.Resize(224))
trans = transforms.Compose(trans)
mnist_train = torchvision.datasets.FashionMNIST(
    root="./data", train=True, transform=trans, download=True)
mnist_test = torchvision.datasets.FashionMNIST(
    root="./data", train=False, transform=trans, download=True)
batch_size = 256
train_iter = data.DataLoader(mnist_train, batch_size, shuffle=True)
test_iter = data.DataLoader(mnist_test, batch_size, shuffle=True)

Fashion-MNIST图像的分辨率（28*28像素）低于ImageNet图像。 为了解决这个问题，我们将它们增加到224
（通常来讲这不是一个明智的做法，但在这里这样做是为了有效使用AlexNet架构）

In [11]:
opt = torch.optim.SGD(net.parameters(),lr = 0.01)
loss = nn.CrossEntropyLoss()
device = 'cuda:0'
net.to(device)
for i in range(10):
    net.train()
    tl =0
    #mini batch
    for p,(X,y) in enumerate(train_iter):
        X,y = X.to(device),y.to(device)
        opt.zero_grad()
        y_pred = net(X)
        l = loss(y_pred,y)
        tl+=l
        l.backward()
        opt.step()
    print("epoch :{},total_loss:{}".format(i,tl))

epoch :0,total_loss:540.9822998046875
epoch :1,total_loss:540.64013671875
epoch :2,total_loss:539.6915893554688
epoch :3,total_loss:454.7789306640625
epoch :4,total_loss:249.08554077148438
epoch :5,total_loss:213.291259765625
epoch :6,total_loss:194.68470764160156
epoch :7,total_loss:181.1240997314453
epoch :8,total_loss:169.7726287841797
epoch :9,total_loss:157.65185546875


In [14]:
from ptflops import get_model_complexity_info
model_name = 'AlexNet'
flops, params = get_model_complexity_info(net, (1, 224, 224), as_strings=True, 
print_per_layer_stat=True)
print("%s |%s |%s" % (model_name, flops, params))

Sequential(
  46.76 M, 100.000% Params, 939.85 MMac, 100.000% MACs, 
  (0): Conv2d(11.71 k, 0.025% Params, 34.15 MMac, 3.634% MACs, 1, 96, kernel_size=(11, 11), stride=(4, 4))
  (1): ReLU(0, 0.000% Params, 279.94 KMac, 0.030% MACs, )
  (2): MaxPool2d(0, 0.000% Params, 279.94 KMac, 0.030% MACs, kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  (3): Conv2d(614.66 k, 1.314% Params, 415.51 MMac, 44.210% MACs, 96, 256, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
  (4): ReLU(0, 0.000% Params, 173.06 KMac, 0.018% MACs, )
  (5): MaxPool2d(0, 0.000% Params, 173.06 KMac, 0.018% MACs, kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  (6): Conv2d(885.12 k, 1.893% Params, 127.46 MMac, 13.561% MACs, 256, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (7): ReLU(0, 0.000% Params, 55.3 KMac, 0.006% MACs, )
  (8): Conv2d(1.33 M, 2.839% Params, 191.16 MMac, 20.339% MACs, 384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (9): ReLU(0, 0.000% 

# vgg net ->使用块的网络（VGG）
而一个VGG块与之类似，由一系列卷积层组成，后面再加上用于空间下采样的最大汇聚层。

In [1]:
import torch
from torch import nn


def vgg_block(num_convs, in_channels, out_channels):
    layers = []
    for _ in range(num_convs):
        layers.append(nn.Conv2d(in_channels, out_channels,
                                kernel_size=3, padding=1))
        layers.append(nn.ReLU())
        #or layers = nn.Sequential()  
        #layers.add_module(nn.xxx) or add_module(name="mymodel{}".format(i),module=nn.Linear(i,i+1))
        in_channels = out_channels
    layers.append(nn.MaxPool2d(kernel_size=2,stride=2))
    return nn.Sequential(*layers)

In [2]:
vgg_block(2,5,5)

Sequential(
  (0): Conv2d(5, 5, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU()
  (2): Conv2d(5, 5, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU()
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)

# VGG 的构建


In [3]:
conv_arch = ((1, 64), (1, 128), (2, 256), (2, 512), (2, 512))
def vgg(conv_arch):
    conv_blks = []
    in_channels = 1
    # 卷积层部分
    for (num_convs, out_channels) in conv_arch:
        conv_blks.append(vgg_block(num_convs, in_channels, out_channels))
        in_channels = out_channels

    return nn.Sequential(
        *conv_blks, nn.Flatten(),
        # 全连接层部分
        nn.Linear(out_channels * 7 * 7, 4096), nn.ReLU(), nn.Dropout(0.5),
        nn.Linear(4096, 4096), nn.ReLU(), nn.Dropout(0.5),
        nn.Linear(4096, 10))

net = vgg(conv_arch)

In [4]:
X = torch.randn(size=(1, 1, 224, 224))
for blk in net:
    X = blk(X)
    print(blk.__class__.__name__,'output shape:\t',X.shape)

Sequential output shape:	 torch.Size([1, 64, 112, 112])
Sequential output shape:	 torch.Size([1, 128, 56, 56])
Sequential output shape:	 torch.Size([1, 256, 28, 28])
Sequential output shape:	 torch.Size([1, 512, 14, 14])
Sequential output shape:	 torch.Size([1, 512, 7, 7])
Flatten output shape:	 torch.Size([1, 25088])
Linear output shape:	 torch.Size([1, 4096])
ReLU output shape:	 torch.Size([1, 4096])
Dropout output shape:	 torch.Size([1, 4096])
Linear output shape:	 torch.Size([1, 4096])
ReLU output shape:	 torch.Size([1, 4096])
Dropout output shape:	 torch.Size([1, 4096])
Linear output shape:	 torch.Size([1, 10])


In [5]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
# 通过ToTensor实例将图像数据从PIL类型变换成32位浮点数格式，
# 并除以255使得所有像素的数值均在0～1之间
trans = [transforms.ToTensor()]
trans.insert(0, transforms.Resize(224))
trans = transforms.Compose(trans)
mnist_train = torchvision.datasets.FashionMNIST(
    root="./data", train=True, transform=trans, download=True)
mnist_test = torchvision.datasets.FashionMNIST(
    root="./data", train=False, transform=trans, download=True)
batch_size = 256
train_iter = data.DataLoader(mnist_train, batch_size, shuffle=True)
test_iter = data.DataLoader(mnist_test, batch_size, shuffle=True)

In [6]:
ratio = 8
small_conv_arch = [(pair[0], pair[1] // ratio) for pair in conv_arch]
net = vgg(small_conv_arch)

In [8]:
opt = torch.optim.SGD(net.parameters(),lr = 0.05)
loss = nn.CrossEntropyLoss()
device = 'cuda:0'
net.to(device)
for i in range(10):
    net.train()
    tl =0
    #mini batch
    for p,(X,y) in enumerate(train_iter):
        X,y = X.to(device),y.to(device)
        opt.zero_grad()
        y_pred = net(X)
        l = loss(y_pred,y)
        tl+=l
        l.backward()
        opt.step()
    print("epoch :{},total_loss:{}".format(i,tl))

epoch :0,total_loss:537.9888916015625
epoch :1,total_loss:238.814697265625
epoch :2,total_loss:138.425048828125
epoch :3,total_loss:108.85270690917969
epoch :4,total_loss:95.05948638916016
epoch :5,total_loss:84.94023132324219
epoch :6,total_loss:77.22953796386719
epoch :7,total_loss:71.08846282958984
epoch :8,total_loss:66.3192138671875
epoch :9,total_loss:62.36429977416992


# NiN 网络
nin块中采用了1\*1 conv 其作用相当于在channel 方向（个人理解为垂直的方向）对每个图像对应位置的像素采用全连接层。即将空间维度中的每个像素视为单个样本，将通道维度视为不同特征（feature）。

In [1]:
import torch
from torch import nn

def nin_block(in_channels, out_channels, kernel_size, strides, padding):
    return nn.Sequential(
        nn.Conv2d(in_channels, out_channels, kernel_size, strides, padding),
        nn.ReLU(),
        nn.Conv2d(out_channels, out_channels, kernel_size=1), nn.ReLU(),
        nn.Conv2d(out_channels, out_channels, kernel_size=1), nn.ReLU())

NiN和AlexNet之间的一个显著区别是NiN完全取消了全连接层。 相反，NiN使用一个NiN块，其输出通道数等于标签类别的数量。最后放一个全局平均汇聚层（global average pooling layer），生成一个对数几率 （logits）。NiN设计的一个优点是，它显著减少了模型所需参数的数量。然而，在实践中，这种设计有时会增加训练模型的时间。

In [6]:
net = nn.Sequential(
    nin_block(1, 96, kernel_size=11, strides=4, padding=0),
    nn.MaxPool2d(3, stride=2),
    nin_block(96, 256, kernel_size=5, strides=1, padding=2),
    nn.MaxPool2d(3, stride=2),
    nin_block(256, 384, kernel_size=3, strides=1, padding=1),
    nn.MaxPool2d(3, stride=2),
    nn.Dropout(0.5),
    # 标签类别数是10
    nin_block(384, 10, kernel_size=3, strides=1, padding=1),
    nn.AdaptiveAvgPool2d((1, 1)),#自适应的pool层，参数为每个样本的预期输出size
    # 将四维的输出转成二维的输出，其形状为(批量大小,10)
    nn.Flatten())

In [9]:
X = torch.rand(size=(1, 1, 224, 224))
for layer in net:
    X = layer(X)
    print(layer.__class__.__name__,'output shape:\t', X.shape)

Sequential output shape:	 torch.Size([1, 96, 54, 54])
MaxPool2d output shape:	 torch.Size([1, 96, 26, 26])
Sequential output shape:	 torch.Size([1, 256, 26, 26])
MaxPool2d output shape:	 torch.Size([1, 256, 12, 12])
Sequential output shape:	 torch.Size([1, 384, 12, 12])
MaxPool2d output shape:	 torch.Size([1, 384, 5, 5])
Dropout output shape:	 torch.Size([1, 384, 5, 5])
Sequential output shape:	 torch.Size([1, 10, 5, 5])
AdaptiveAvgPool2d output shape:	 torch.Size([1, 10, 1, 1])
Flatten output shape:	 torch.Size([1, 10])


In [13]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
# 通过ToTensor实例将图像数据从PIL类型变换成32位浮点数格式，
# 并除以255使得所有像素的数值均在0～1之间
trans = [transforms.ToTensor()]
trans.insert(0, transforms.Resize(224))
trans = transforms.Compose(trans)
mnist_train = torchvision.datasets.FashionMNIST(
    root="./data", train=True, transform=trans, download=True)
mnist_test = torchvision.datasets.FashionMNIST(
    root="./data", train=False, transform=trans, download=True)
batch_size = 128
train_iter = data.DataLoader(mnist_train, batch_size, shuffle=True)
test_iter = data.DataLoader(mnist_test, batch_size, shuffle=True)

In [18]:
def init_weights(m):
        if type(m) == nn.Linear or type(m) == nn.Conv2d:
            nn.init.xavier_uniform_(m.weight)
net.apply(init_weights)

Sequential(
  (0): Sequential(
    (0): Conv2d(1, 96, kernel_size=(11, 11), stride=(4, 4))
    (1): ReLU()
    (2): Conv2d(96, 96, kernel_size=(1, 1), stride=(1, 1))
    (3): ReLU()
    (4): Conv2d(96, 96, kernel_size=(1, 1), stride=(1, 1))
    (5): ReLU()
  )
  (1): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  (2): Sequential(
    (0): Conv2d(96, 256, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): ReLU()
    (2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (3): ReLU()
    (4): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (5): ReLU()
  )
  (3): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): Conv2d(256, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): Conv2d(384, 384, kernel_size=(1, 1), stride=(1, 1))
    (3): ReLU()
    (4): Conv2d(384, 384, kernel_size=(1, 1), stride=(1, 1))
    (5): ReLU()
  )
  (5): MaxPool2d(kernel_size=3, stri

In [19]:
#如果不初始化，则会训练过程中无法迭代，进入局部最小，loss不降。
opt = torch.optim.SGD(net.parameters(),lr = 0.01)
loss = nn.CrossEntropyLoss()
device = 'cuda:0'
net.to(device)
for i in range(10):
    net.train()
    tl =0
    #mini batch
    for p,(X,y) in enumerate(train_iter):
        X,y = X.to(device),y.to(device)
        opt.zero_grad()
        y_pred = net(X)
        l = loss(y_pred,y)
        tl+=l
        l.backward()
        opt.step()
    print("epoch :{},total_loss:{}".format(i,tl))

epoch :0,total_loss:1080.4974365234375
epoch :1,total_loss:1079.8900146484375
epoch :2,total_loss:1079.71728515625
epoch :3,total_loss:1079.33740234375
epoch :4,total_loss:1078.1181640625
epoch :5,total_loss:1075.228271484375
epoch :6,total_loss:1069.063232421875
epoch :7,total_loss:1020.052001953125
epoch :8,total_loss:838.4521484375
epoch :9,total_loss:667.083251953125


# Googlenet 并行连接网络
基本卷积块称为 Inception block

In [1]:
#tbd

# 序列模型

In [1]:
#自回归模型
import torch
from torch import nn

point_num = 1000
time = torch.arange(1,point_num+1,dtype=torch.float32)
x = torch.sin(0.01 * time) + torch.normal(0,0.02,(point_num,))
x.shape

torch.Size([1000])

In [3]:
# create data
tau = 4
features = torch.zeros((point_num - tau, tau))
for i in range(tau):
    features[:,i] = x[i:point_num - tau + i]
labels = x[tau:].reshape((-1,1))

In [11]:
batch_size = 64
n_train = 600

from torch.utils import data
dataset = data.TensorDataset(*(features[:n_train], labels[:n_train]))
#from torch.utils import data
#dataset = data.TensorDataset(features[:n_train], labels[:n_train])
dataset
#remain to do mlp to predict results